tags:
  - name: products
    description: products API

paths:
  /product/{id}:
    get:
      tags:
        - products
      summary: Find Product By Id
      parameters:
        - name: id
          type: string
          in: path
          description: Product Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  product:
    type: object
    properties:
      product:
        type: object
      reviews:
        type: array
        items:
          $ref: "#/definitions/review"
      summary:
        $ref: "#/definitions/summary"
  review:
    type: object
    required:
      - score
      - productId
    properties:
      productId:
        type: string
        description: product id
      score:
        type: integer
        format: int64
  summary:
    type: object
    required:
      - averageRating
      - productId
      - reviews
    properties:
      productId:
        type: string
        description: product id
      averageRating:
        type: integer
        format: int64
      reviews:
        type: integer
        format: int32
